### ISSUE TITLE
new xoops_confirm

### ISSUE THREAD

**Issue by ggoffy** [XoopsDocs/modulebuilder-tutorial#10]
Currently it is not possible to render xoops confirm and to add it with smary assign to the template.
To avoid broken template design this should be possible.

Maybe xoops confirm should be modal.

**Comment by mambax7** [comment]
Why is it in the https://github.com/XoopsDocs/modulebuilder-tutorial/ ? 
Shouldn't all the issues be reported in: 
https://github.com/XoopsModules25x/modulebuilder/ ?

**Comment by ggoffy** [comment]
wrong branch :(
